# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site favicons & manifest icons
# 9. Site navigation

remote_theme: daviddarnes/alembic

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- alembic-jekyll-theme.gemspec
- .jekyll-cache

# 2. Installed Gems
plugins:
- jekyll-remote-theme
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji

# 3. Gem settings
paginate: 3 # jekyll-paginate > items per page
paginate_path: blog/page:num # jekyll-paginate > blog page
jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
twitter:
  username: sdsvc # jekyll-seo-tag > Owners twitter username
author: HosseinZeinali # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: Hossein Zeinali # jekyll-seo-tag > real name
#  links:  # jekyll-seo-tag > social aliases (sameAs)
#    - https://twitter.com/DavidDarnes
#    - https://www.facebook.com/daviddarnes
#    - https://www.linkedin.com/in/daviddarnes
#    - https://github.com/daviddarnes
# markdown: CommonMark # Markdown parse settings, CommonMark performs slightly better an others in build time
# commonmark:
  # options: ["SMART", "FOOTNOTES"]
  # extensions: ["strikethrough", "autolink", "table"]

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Europe/London # Timezone for blog posts and alike

# 5. Collections
collections:
  posts:
    title: Posts # Needed for Siteleaf
    output: true
    description: "Posts and News About SdSV Challenge 2020" # The post list page content
    feature_text: |
      Welcome to the SdSV Challenge blog
    feature_image: "https://picsum.photos/2560/600?image=986"

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
    values:
      image: "/assets/default-social-image.png" # Default image for sharing

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
lang: en-GB # Set the site language
title: "SdSV Challenge 2020" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/logos/logo.svg" # Site logo, also used in jekyll-seo-tag
description: "The SdSV challenge evaluates speaker recognition technologies in a short duration scenario and with varying degree of phonetic overlap between the enrollment and test utterances." # Site description and default description, also used in jekyll-seo-tag
url: "https://sdsvc.github.io" # Site url, also used in jekyll-seo-tag
baseurl: ""
repo: "https://github.com/SdSVC/sdsvc.github.io"
email: "sdsvc2020@gmail.com"
# disqus: "alembic-1" # Blog post comments, uncomment the option and set the site ID from your Disqus account
# google_analytics: ''
# google_analytics_anonymize_ip: ''
# service_worker: false # Will turn off the service worker if set to false
css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference

# 8. Site favicons & manifest icons
favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
  16: '/assets/logos/logo@16px.png'
  32: '/assets/logos/logo@32px.png'
  96: '/assets/logos/logo@96px.png'
  120: '/assets/logos/logo@120px.png'
  144: '/assets/logos/logo@144px.png'
  180: '/assets/logos/logo@180px.png'
  512: '/assets/logos/logo@512px.png'
  1024: '/assets/logos/logo@1024px.png'

# 9. Site navigation
navigation_header:
- title: Home
  url: /
- title: Organizers
  url: /organizers/
#- title: Blog
#  url: /blog/
- title: Registration
  url: /registration/
- title: Results
  url: /results/
- title: Descriptions
  url: /mydescriptions/
- title: Workshop
  url: /workshop/
- title: Search
  url: /search/

navigation_footer:
- title: SdSV Challenge 2020
  url: https://sdsvc.github.io

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
#  Twitter: https://twitter.com/DavidDarnes
#  LinkedIn: https://www.linkedin.com/in/daviddarnes
#  GitHub: https://github.com/daviddarnes
#  link: https://darn.es
  RSS: /feed.xml

sharing_links: # Appear at the bottom of single blog posts, add as desired. The value can be 'true' or the desired button colour
  Twitter: "#0d94e7"
  facebook: "#3B5998"
  Email: true

