remote_theme: daviddarnes/alembic

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- alembic-jekyll-theme.gemspec
- .jekyll-cache

# 2. Installed Gems
plugins:
- jekyll-remote-theme
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji

# 3. Gem settings
paginate: 3 # jekyll-paginate > items per page
paginate_path: blog/page:num # jekyll-paginate > blog page
jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying

encoding: utf-8 # Make sure the encoding is right
lang: en-GB # Set the site language
title: "SdSV Challenge 2020" # Site name or title, also used in jekyll-seo-tag
#logo: "/images/VOiCES_logo.png" # Site logo, also used in jekyll-seo-tag
description: "The webpage for Short-duration Speaker Verification Challenge 2020." # Site description and default description, also used in jekyll-seo-tag
#url: "https://lab41.org" # Site url, also used in jekyll-seo-tag
baseurl: ""
repo: "https://github.com/sdsvc.github.io"
email: "sdsvc2020@gmail.com"
# disqus: "alembic-1" # Blog post comments, uncomment the option and set the site ID from your Disqus account
#avatarurl: "/assets/speech.ico" # "https://www.gravatar.com/avatar/6c0377abcf4da91cdd35dea4554b2a4c" # Uses avatars for favicons to get multple sites, eg Gravatar, Twitter, GitHub
# google_analytics: ''
# service_worker: false # Will turn off the service worker if set to false
css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference

# 9. Site navigation
navigation_header:
- title: Home
  url: /
- title: Elements
  url: /elements/
- title: Blog
  url: /blog/
- title: Organizers
  url: /organizers/
- title: Search
  url: /search/
- title: Fork Alembic
  url: https://github.com/daviddarnes/alembic


